AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable

Style/WordArray:
  Enabled: false

Style/RedundantInterpolation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/HashAlignment:
  Enabled: false
